# Generated by Django 5.0.6 on 2024-05-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_pokemon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="abilities",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="types",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
